# Generated by Django 2.1.7 on 2025-03-29 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250328_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 29, 9, 5, 20, 841743)),
        ),
    ]
